INSERT INTO ADDRESS(ADDRESS, CITY, STATE, ZIP) VALUES ('STREET', 'SEOUL', 'STATE', '11111');
INSERT INTO ADDRESS(ADDRESS, CITY, STATE, ZIP) VALUES ('STREET', 'BUSAN', 'STATE', '22222');
INSERT INTO ADDRESS(ADDRESS, CITY, STATE, ZIP) VALUES ('STREET', 'INCHON', 'STATE', '33333');

INSERT INTO PERSON(ADDRESS_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER)
VALUES('1','gildong@gmail.com','GILDONG','HONG','010-1234-1234');

INSERT INTO PERSON(ADDRESS_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER)
VALUES('2','gil@gmail.com','GIL','PARK','010-1111-2222');

INSERT INTO PERSON(ADDRESS_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER)
VALUES('3','dong@gmail.com','DONG','KIM','010-3333-4444');

